### ISSUE TITLE
How to do data preprocessing

### ISSUE THREAD

**Issue by CodeOfAlex** [annabechang/Propaganda_Tech_Twitter_PRC#1]
Sorry to bother you，I want to run the model using the datasets，but can‘t find the jupyter notebook which mentioned in the article can help reference on data preprocessing steps，is it released？

**Comment by annabechang** [comment]
Hi,
Thanks for reaching out. Sorry for late reply, have been busy with other stuffs. I just uploaded it, hope you will find it helpful.
